
logging:
  level:
    io.kapsules: info

management:
  endpoints:
    web:
      exposure:
        include: "env, info, health"

secrets:
  keypair:
    private: "private/ec-key-1.pem"
    pub: "private/ec-key-pub.pem"

---
spring:
  profiles: debug

secrets:
  secret: "zekret"

logging:
  level:
    io.kapsules: debug
    reactor.netty: warn

management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  profiles: test
logging:
  level:
    io.kapsules: debug
    reactor.netty: warn

secrets:
  secret: "test"
