# JWT / OPA Demo application configuration
#
# Created by M. Massenzio, 2020-11-22

logging:
  level:
    io.kapsules: info

management:
  endpoints:
    web:
      exposure:
        include: "env, info, health"

# This is used to build the Rule validation endpoint:
#   /v1/data/kapsules/allow
opa:
  policy: kapsules
  rule: allow

---
spring:
  profiles: debug

# TODO: in Production this should be configured via env properties, or a "well-known location"
secrets:
  secret: "zekret"
  keypair:
    private: "private/ec-key.pem"
    pub: "private/ec-key-pub.pem"


logging:
  level:
    io.kapsules: debug
    reactor.netty: warn

management:
  endpoints:
    web:
      exposure:
        include: "*"

# OPA Server running in a local container:
#    docker run -d --rm -p 8181:8181 --name opa openpolicyagent/opa run --server
opa:
  server: "localhost:8181"
